language: node_js
node_js:
  - "10"

dist: xenial
sudo: required
services:
  - xvfb

addons:
  firefox: "latest"

before_script:
  - export DISPLAY=:99.0
  - (cd web-app && npm install)
  - (cd server && npm install)

script:
  - (cd server && npm run test)
  - (cd server && npm run lint)
  - (cd web-app && npm run lint)
  - (cd web-app && ng build --prod)