language: node_js
node_js:
  - "10"

addons:
  firefox: "latest"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - (cd web-app && npm install)
  - (cd server && npm install)

script:
  - (cd web-app && npm run test -- --browsers Firefox --watch=false)
  - (cd web-app && npm run lint)
  - (cd server && npm run test)
  - (cd server && npm run lint)
