language: node_js
node_js:
  - "iojs"
  - "7"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd web-app
  - npm install
  - cd ../server
  - npm install
  - cd ..

script:
  - cd web-app
  - npm run test -- --browsers Firefox --single-run
  - npm run lint
  - cd ../server
  - npm run test
