= Server

Express.js server running in node

== Build
`npm run start` to run dev server. Can be hit at `http://localhost:4000/`.

== Running unit tests
`npm run test` to for tests

== Deploying to server
Requirements:

 * https://www.docker.com/[Docker] must be installed.

Steps:

 . Build docker container using `npm run build:docker`
 . Run container using `docker run --name server -p 4000:4000 --restart on-failure -d server`

Other commands:

 * `docker ps` to list running containers
 * For deleting containers refer to https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes[this]

== How to install PostgresSQL

If Linux then follow instructions at https://www.postgresql.org/download/linux/ubuntu/[here].
Then follow instructions https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-16-04[here] on setting up the database.
For local dev usage use username/password/db as "solarcar". To connect via TCP, log in as solarcar `sudo -u solarcar psql solarcar` and run `ALTER USER "solarcar" with PASSWORD 'solarcar';`.

To reset database: login as solarcar user and run
`DROP SCHEMA public CASCADE;` followed by `CREATE SCHEMA public;`.

== Debugging

Summary:

1. Run `node --inspect-brk app.js`
2. Navigate to `about:inspect` in Chrome

Reference:

* https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27
* https://nodejs.org/en/docs/inspector
