= Server

Express.js server running in node

== Deploying Server
First, SSH into the server IP
`ssh root@138.197.206.227` 
Refer to Passwords Document or talk to current manager
`cd Epsilon-Telemetry-Server`
`git pull`
`ng build —prod`
`cp dist/*  to var/www/html/ -rf`

`exit` to leave

== Build
`npm run start` to run dev server. Can be hit at `http://localhost:4000/`.

== Setting up PostgreSQL
=== Prerequisites
First, you'll need to get the PostgreSQL signing key: +
....
wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O- | sudo apt-key add -
....

Add the PostgreSQL repository information with: +
....
echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" | sudo tee /etc/apt/sources.list.d/postgresql.list
....

=== Installation
Install PostgreSQL +
....
 sudo apt-get update
 sudo apt-get install postgresql
....

=== Setting up the Database
In order to setup the database with the telemetry schema, you'll need to migrate the same schema from the database on our DigitalOcean droplet. To start, create the database, user, and password. Replace `username_here` with the username you want and follow the prompts to select a password as well.
....
sudo -u postgres createdb epsilontelemetrydb
sudo -u postgres createuser username_here -s -d -W
....
You can verify that the database and user were created with psql:
....
sudo -u postgres psql
....
While in the psql prompt, `\l` lists the databases and `\du` lists the users. You can quit with vim-style commands by typing `:q`. You can then quit with the `\quit` command.

Creating a user doesn't make the password, to set the password:
....
sudo -u postgres psql
....
Then in postgres:
....
\password user_name
....
Finally, import the schema (file is at the root of this repository)
....
sudo -u postgres psql epsilontelemetrydb < migrate.psql
....

=== Setting up Node configuration
Create a file at the root of this directory called `config.js`. You can change different parameters depending on how you've set up your working environment. Below is the default configuration found in `config.js.example`:
....
module.exports.server = {
  port : 4000,
}

module.exports.database = {
  user: 'epsilon',
  database: 'epsilontelemetrydb',
  password: 'UCalgarySolar',
  port: 5432,
}

module.exports.rabbitmq = {
  host: 'amqp://localhost:5672',
  queue_name: 'msgQueue',
  exchange_name : 'hermesExchange',
}
....

== Running unit tests
`npm run test` to run tests

== Deploying to server
Requirements:

 * https://www.docker.com/[Docker] must be installed.

Steps:

 . Build docker container using `npm run build:docker`
 . Run container using `docker run --name server -p 4000:4000 --restart on-failure -d server`

Other commands:

 * `docker ps` to list running containers
 * For deleting containers refer to https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes[this]

