= Server

Express.js server running in node

== Build
`npm run start` to run dev server. Can be hit at `http://localhost:4000/`.

== Setting up PostgreSQL
=== Prerequisites
First, you'll need to get the PostgreSQL signing key: +
....
wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O- | sudo apt-key add -
....

Add the PostgreSQL repository information with: +
....
echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" | sudo tee /etc/apt/sources.list.d/postgresql.list
....

=== Installation
Install PostgreSQL +
....
 sudo apt-get update
 sudo apt-get install postgresql
....

=== Setting up the Database
In order to setup the database with the telemetry schema, you'll need to migrate the same schema from the database on our DigitalOcean droplet. To start, create the database using the postgres user
....
sudo -u postgres createdb epsilontelemetrydb
....
Next, enter the PostgreSQL console as the user postgres
....
sudo -u postgres psql
....
You'll be in console mode now; you need to create the user epsilon
....
CREATE USER epsilon WITH PASSWORD 'UCalgarySolar' CREATEDB SUPERUSER;
\quit
....
Finally, import the schema (file is at the root of this repository) +
....
sudo -u postgres psql epsilontelemetrydb < migrate.psql
....
== Running unit tests
`npm run test` to run tests

== Deploying to server
Requirements:

 * https://www.docker.com/[Docker] must be installed.

Steps:

 . Build docker container using `npm run build:docker`
 . Run container using `docker run --name server -p 4000:4000 --restart on-failure -d server`

Other commands:

 * `docker ps` to list running containers
 * For deleting containers refer to https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes[this]

