export interface ILapDataInterface {
    lapnumber: number,
    secondsdifference: number,
    totalpowerin: number,
    totalpowerout: number,
    netpowerout: number,
    distance: number,
    amphours: number,
    averagepackcurrent: number,
    batterysecondsremaining: number,
    lapsremaining: number,
    averagespeed: number,
    label: string,
    driver: string,
}
