name: Web App CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: web-app
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm install
    - run: npm install -g @angular/cli
    - run: npm run lint
    - run: npx stylelint src/**.css
    - run: ng build --prod